<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'EMAIL_SUBJECT_RECOVERY' => 'Код восстановления пароля.',
    'EMAIL_SUBJECT_SIGNUP' => 'Код подтверждения новой учётной записи.',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'В момент обноеления профиля возникла ошибка. Попробуйте ещё раз пожалуйста!',
    'FRONTEND_FLASH_SUCCES_UPDATE' => 'Профиль был успешно обновлён.',
    'ATTR_CREATED' => 'Дата создания',
    'ATTR_EMAIL' => 'E-mail',
    'ATTR_NAME' => 'Имя',
    'ATTR_NEW_EMAIL' => 'Новый e-mail',
    'ATTR_NEW_PASSWORD' => 'Новый пароль',
    'ATTR_NEW_REPASSWORD' => 'Повторите новый пароль',
    'ATTR_OLDEMAIL' => 'Текущий e-mail',
    'ATTR_OLDPASSWORD' => 'текущий пароль',
    'ATTR_PASSWORD' => 'Пароль',
    'ATTR_REMEMBER_ME' => 'Запомнить меня',
    'ATTR_REPASSWORD' => 'Повторите пароль',
    'ATTR_ROLE' => 'Роль',
    'ATTR_SECURE_KEY' => 'Ключ безопасности',
    'ATTR_STATUS' => 'Статус',
    'ATTR_SURNAME' => 'Фамилия',
    'ATTR_UPDATED' => 'Дата обновления',
    'ATTR_USERNAME' => 'Логин',
    'BACKEND_CREATE_SUBMIT' => 'Сохранить',
    'BACKEND_CREATE_TITLE' => 'Создать нового пользователя',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'В момент создания нового пользователя возникла ошибка.',
    'BACKEND_INDEX_TITLE' => 'Страница пользователей',
    'BACKEND_LOGIN_OR' => 'или',
    'BACKEND_LOGIN_RECOVERY' => 'Восстановить пароль',
    'BACKEND_LOGIN_SUBMIT' => 'Войти',
    'BACKEND_LOGIN_TITLE' => 'Авторизация',
    'BACKEND_PROMPT_ROLE' => 'Выберите роль',
    'BACKEND_PROMPT_STATUS' => 'Выберите статус',
    'BACKEND_UPDATE_SUBMIT' => 'Обновить',
    'BACKEND_UPDATE_TITLE' => 'Обновить пользователя',
    'BACKEND_VIEW_TITLE' => 'Страница пользователя',
    'EMAIL_SUBJECT_CHANGE' => 'Код подтверждения новой электронной почты.',
    'ERROR_MSG_INVALID_OLD_PASSWORD' => 'Неправильный текущий пароль',
    'ERROR_MSG_INVALID_USERNAME_OR_PASSWORD' => 'Неправильный логин или пароль',
    'FRONTEND_EMAIL_CHANGE_SUBMIT' => 'Изменить',
    'FRONTEND_EMAIL_CHANGE_TITLE' => 'Изменение адреса электронной почты',
    'FRONTEND_FLASH_FAIL_ACTIVATION' => 'Неверный код активации или возмоможно аккаунт был уже ранее активирован.',
    'FRONTEND_FLASH_FAIL_EMAIL_CHANGE' => 'В момент изменения электронного адреса возникла ошибка. Попробуйте ещё раз пожалуйста!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION' => 'В момент подтверждения нового электронного адреса возникла ошибка. Попробуйте ещё раз пожалуйста!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION_WITH_INVALID_KEY' => 'Неверный код подтверждения.',
    'FRONTEND_FLASH_FAIL_PASSWORD_CHANGE' => 'В момент изменения пароля возникла ошибка. Попробуйте ещё раз пожалуйста!',
    'FRONTEND_FLASH_FAIL_RECOVERY' => 'В момент отправки письма возникла ошибка. Попробуйте ещё раз пожалуйста!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION' => 'В момент подтверждения нового пароля возникла ошибка. Попробуйте ещё раз пожалуйста!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION_WITH_INVALID_KEY' => 'Неверный код подтверждения.',
    'FRONTEND_FLASH_FAIL_RESEND' => 'В момент отправки письма возникла ошибка. Попробуйте ещё раз пожалуйста!',
    'FRONTEND_FLASH_FAIL_SIGNUP' => 'В момент регистрации возникла ошибка. Попробуйте ещё раз пожалуйста!',
    'FRONTEND_FLASH_SUCCESS_ACTIVATION' => 'Ваша учётная запись была успешно активирована.',
    'FRONTEND_FLASH_SUCCESS_NEW_EMAIL_CONFIRMATION' => 'E-mail адрес был успешно обновлён!',
    'FRONTEND_FLASH_SUCCESS_PASSWORD_CHANGE' => 'Пароль был успешно обновлён!',
    'FRONTEND_FLASH_SUCCESS_RECOVERY' => 'На указанный вами электронный адрес было отправлено письмо с кодом восстановления пароля.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY_CONFIRMATION' => 'Пароль был успешно восстановлен.',
    'FRONTEND_FLASH_SUCCESS_RESEND' => 'На указанный электронный адрес было отправлено письмо с кодом активации новой учётной записи.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITHOUT_LOGIN' => 'Учётная запись была успешно создана. Через несколько секунд вам на почту будет отправлен код для активации аккаунта. В случае если письмо не пришло в течении 15 минут, вы можете заново запросить отправку ключа по данной <a href="{url}">ссылке</a>.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITH_LOGIN' => 'Учётная запись была успешно создана.',
    'FRONTEND_FLASH_SUCCES_EMAIL_CHANGE' => 'На указанный новый электронный адрес было отправлено письмо с кодом подтверждения.',
    'FRONTEND_INDEX_TITLE' => 'Пользователи',
    'FRONTEND_LOGIN_OR' => 'или',
    'FRONTEND_LOGIN_RECOVERY' => 'Восстановить пароль',
    'FRONTEND_LOGIN_SUBMIT' => 'Войти',
    'FRONTEND_LOGIN_TITLE' => 'Авторизация',
    'FRONTEND_PASSWORD_CHANGE_SUBMIT' => 'Изменить',
    'FRONTEND_PASSWORD_CHANGE_TITLE' => 'Смена пароля',
    'FRONTEND_RECOVERY_CONFIRMATION_SUBMIT' => 'Сохранить',
    'FRONTEND_RECOVERY_CONFIRMATION_TITLE' => 'Восстановление пароля',
    'FRONTEND_RECOVERY_SUBMIT' => 'Восстановить',
    'FRONTEND_RECOVERY_TITLE' => 'Восстановления пароля',
    'FRONTEND_RESEND_SUBMIT' => 'Отправить',
    'FRONTEND_RESEND_TITLE' => 'Повторная отправка e-mail подтверждения',
    'FRONTEND_SIGNUP_RESEND' => 'Повторная отправка e-mail подтверждения',
    'FRONTEND_SIGNUP_SUBMIT' => 'Зарегистрироватся',
    'FRONTEND_SIGNUP_TITLE' => 'Регистрация',
    'FRONTEND_UPDATE_SUBMIT' => 'Обновить',
    'FRONTEND_UPDATE_TITLE' => 'Редактирование профиля',
    'STATUS_ACTIVE' => 'Активный',
    'STATUS_BANNED' => 'Забаненый',
    'STATUS_INACTIVE' => 'Неактивный',
];
