<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'EMAIL_SUBJECT_RECOVERY' => 'Код відновлення паролю.',
    'EMAIL_SUBJECT_SIGNUP' => 'Код підтвердження нового облікового запису.',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'В момент оновлення профілю виникла помилка. Спробуйте ще раз, будь ласка!',
    'FRONTEND_FLASH_SUCCES_UPDATE' => 'Профіль був успішно оновлений.',
    'ATTR_CREATED' => 'Дата створення',
    'ATTR_EMAIL' => 'E-mail',
    'ATTR_NAME' => 'Ім\'я',
    'ATTR_NEW_EMAIL' => 'Новий e-mail',
    'ATTR_NEW_PASSWORD' => 'Новий пароль',
    'ATTR_NEW_REPASSWORD' => 'Повторіть новий пароль',
    'ATTR_OLDEMAIL' => 'Діючий e-mail',
    'ATTR_OLDPASSWORD' => 'Діючий пароль',
    'ATTR_PASSWORD' => 'Пароль',
    'ATTR_REMEMBER_ME' => 'Запам\'ятати мене',
    'ATTR_REPASSWORD' => 'Повторіть пароль',
    'ATTR_ROLE' => 'Роль',
    'ATTR_SECURE_KEY' => 'Ключ безпеки',
    'ATTR_STATUS' => 'Статус',
    'ATTR_SURNAME' => 'Прізвище',
    'ATTR_UPDATED' => 'Дата оновлення',
    'ATTR_USERNAME' => 'Логін',
    'BACKEND_CREATE_SUBMIT' => 'Зберегти',
    'BACKEND_CREATE_TITLE' => 'Створити нового користувача',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'В момент створення нового користувача виникла помилка.',
    'BACKEND_INDEX_TITLE' => 'Сторінка користувачів',
    'BACKEND_LOGIN_OR' => 'або',
    'BACKEND_LOGIN_RECOVERY' => 'Відновити пароль',
    'BACKEND_LOGIN_SUBMIT' => 'Увійти',
    'BACKEND_LOGIN_TITLE' => 'Авторизація',
    'BACKEND_PROMPT_ROLE' => 'Виберіть роль',
    'BACKEND_PROMPT_STATUS' => 'Виберіть статус',
    'BACKEND_UPDATE_SUBMIT' => 'Оновити',
    'BACKEND_UPDATE_TITLE' => 'Оновити користувача',
    'BACKEND_VIEW_TITLE' => 'Сторінка користувача',
    'EMAIL_SUBJECT_CHANGE' => 'Код підтверждення нової електронної пошти.',
    'ERROR_MSG_INVALID_OLD_PASSWORD' => 'Невірний діючий пароль',
    'ERROR_MSG_INVALID_USERNAME_OR_PASSWORD' => 'Невірний логін або пароль',
    'FRONTEND_EMAIL_CHANGE_SUBMIT' => 'Змінити',
    'FRONTEND_EMAIL_CHANGE_TITLE' => 'Змінити адресу електронної пошти',
    'FRONTEND_FLASH_FAIL_ACTIVATION' => 'Невірний код активації або обліковий запис був активований раніше.',
    'FRONTEND_FLASH_FAIL_EMAIL_CHANGE' => 'В момент зміни електронної адреси виникла помилка. Спробуйте ще раз, будь ласка!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION' => 'В момент підтверждення нової электронної адреси виникла помилка. Спробуйте ще раз, будь ласка!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION_WITH_INVALID_KEY' => 'Невірний код підтверждення.',
    'FRONTEND_FLASH_FAIL_PASSWORD_CHANGE' => 'В момент зміни паролю виникла помилка. Спробуйте ще раз, будь ласка!',
    'FRONTEND_FLASH_FAIL_RECOVERY' => 'В момент відправки листа виникла помилка. Спробуйте ще раз, будь ласка!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION' => 'В момент підтверждення нового паролю виникла помилка. Спробуйте ще раз, будь ласка!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION_WITH_INVALID_KEY' => 'Невірний код підтверждення.',
    'FRONTEND_FLASH_FAIL_RESEND' => 'В момент відправки листа виникла помилка. Спробуйте ще раз, будь ласка!',
    'FRONTEND_FLASH_FAIL_SIGNUP' => 'В момент реєстрації виникла помилка. Спробуйте ще раз, будь ласка!',
    'FRONTEND_FLASH_SUCCESS_ACTIVATION' => 'Ваш обліковий запис був успішно активований.',
    'FRONTEND_FLASH_SUCCESS_NEW_EMAIL_CONFIRMATION' => 'E-mail адрес був успішно оновлений!',
    'FRONTEND_FLASH_SUCCESS_PASSWORD_CHANGE' => 'Пароль був успішно оновлений!',
    'FRONTEND_FLASH_SUCCESS_RECOVERY' => 'На вказану вами електронну адресу було відправлено листа с кодом відновлення паролю.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY_CONFIRMATION' => 'Пароль був успішно відновлений.',
    'FRONTEND_FLASH_SUCCESS_RESEND' => 'На вказану вами електронну адресу було відправлено листа с кодом активації нового облікового запису.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITHOUT_LOGIN' => 'Обліковий запис був успішно створений. Через декілька секунд Вам на пошту буде надісланий код для активації облікового запису. В випадку, якщо лист не надійшов на протязі 15 хвилин, Ви можете запросити відправку ключа іще раз за данним  <a href="{url}">посиланням</a>.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITH_LOGIN' => 'Обліковий запис був успішно створенний.',
    'FRONTEND_FLASH_SUCCES_EMAIL_CHANGE' => 'На вказану нову електронну адресу було відправленно листа з кодом підтверждення.',
    'FRONTEND_INDEX_TITLE' => 'Користувачі',
    'FRONTEND_LOGIN_OR' => 'або',
    'FRONTEND_LOGIN_RECOVERY' => 'Відновити пароль',
    'FRONTEND_LOGIN_SUBMIT' => 'Увійти',
    'FRONTEND_LOGIN_TITLE' => 'Авторизація',
    'FRONTEND_PASSWORD_CHANGE_SUBMIT' => 'Змінити',
    'FRONTEND_PASSWORD_CHANGE_TITLE' => 'Зміна паролю',
    'FRONTEND_RECOVERY_CONFIRMATION_SUBMIT' => 'Зберегти',
    'FRONTEND_RECOVERY_CONFIRMATION_TITLE' => 'Відновлення паролю',
    'FRONTEND_RECOVERY_SUBMIT' => 'Відновлення',
    'FRONTEND_RECOVERY_TITLE' => 'Відновлення паролю',
    'FRONTEND_RESEND_SUBMIT' => 'Відпраити',
    'FRONTEND_RESEND_TITLE' => 'Повторна відправка e-mail підтверждення',
    'FRONTEND_SIGNUP_RESEND' => 'Повторна відправка e-mail підтверждення',
    'FRONTEND_SIGNUP_SUBMIT' => 'Зареєструватися',
    'FRONTEND_SIGNUP_TITLE' => 'Реєстрація',
    'FRONTEND_UPDATE_SUBMIT' => 'Оновити',
    'FRONTEND_UPDATE_TITLE' => 'Редагування профілю',
    'STATUS_ACTIVE' => 'Активний',
    'STATUS_BANNED' => 'Заблокований',
    'STATUS_INACTIVE' => 'Неактивний',
];
