<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'User has not been saved. Please try again!',
    'EMAIL_SUBJECT_CHANGE' => 'Email confirmation token',
    'EMAIL_SUBJECT_RECOVERY' => 'Your password reset request',
    'EMAIL_SUBJECT_SIGNUP' => 'Email confirmation token',
    'FRONTEND_FLASH_FAIL_ACTIVATION' => 'User has not been activated. Please try again!',
    'FRONTEND_FLASH_FAIL_EMAIL_CHANGE' => 'Email has not been changed. Please try again!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION' => 'Email has not been confirmed. Please try again!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION_WITH_INVALID_KEY' => 'Invalid request token.',
    'FRONTEND_FLASH_FAIL_PASSWORD_CHANGE' => 'Password has not been changed. Please try again!',
    'FRONTEND_FLASH_FAIL_RECOVERY' => 'Password recovery failed. Please try again!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION' => 'Password recovery failed. Please try again!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION_WITH_INVALID_KEY' => 'Invalid request token.',
    'FRONTEND_FLASH_FAIL_RESEND' => 'Resend email confirmation failed. Please try again!',
    'FRONTEND_FLASH_FAIL_SIGNUP' => 'User sign up failed. Please try again!',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'Profile update failed. Please try again!',
    'FRONTEND_FLASH_SUCCESS_ACTIVATION' => 'Your Account has been successfully activated. You can now log in using the username and password you chose during the registration.',
    'FRONTEND_FLASH_SUCCESS_NEW_EMAIL_CONFIRMATION' => 'Your email has been successfully confirmed.',
    'FRONTEND_FLASH_SUCCESS_PASSWORD_CHANGE' => 'Your password has been successfully changed.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY' => 'A verification link has been sent to the email address you entered.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY_CONFIRMATION' => 'Reset password successful. You may now login to the site.',
    'FRONTEND_FLASH_SUCCESS_RESEND' => 'A verification link has been sent to the email address you entered.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITHOUT_LOGIN' => 'Your account has been created and a verification link has been sent to the email address you entered.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITH_LOGIN' => 'Your account has been created.',
    'FRONTEND_FLASH_SUCCES_EMAIL_CHANGE' => 'Your email address has been successfully changed.',
    'FRONTEND_FLASH_SUCCES_UPDATE' => 'Your account has been successfully updated.',
    'ATTR_CREATED' => 'Created at',
    'ATTR_EMAIL' => 'E-mail',
    'ATTR_NAME' => 'Name',
    'ATTR_NEW_EMAIL' => 'New e-mail',
    'ATTR_NEW_PASSWORD' => 'New password',
    'ATTR_NEW_REPASSWORD' => 'Repeat new password',
    'ATTR_OLDEMAIL' => 'Current e-mail',
    'ATTR_OLDPASSWORD' => 'Current password',
    'ATTR_PASSWORD' => 'Password',
    'ATTR_REMEMBER_ME' => 'Remember me',
    'ATTR_REPASSWORD' => 'Repeat pssword',
    'ATTR_ROLE' => 'Role',
    'ATTR_SECURE_KEY' => 'Secure key',
    'ATTR_STATUS' => 'Status',
    'ATTR_SURNAME' => 'Surname',
    'ATTR_UPDATED' => 'Updated at',
    'ATTR_USERNAME' => 'Username',
    'BACKEND_CREATE_SUBMIT' => 'Save',
    'BACKEND_CREATE_TITLE' => 'Create new user',
    'BACKEND_INDEX_TITLE' => 'Users page',
    'BACKEND_LOGIN_OR' => 'or',
    'BACKEND_LOGIN_RECOVERY' => 'Recover password',
    'BACKEND_LOGIN_SUBMIT' => 'Log In',
    'BACKEND_LOGIN_TITLE' => 'Log In',
    'BACKEND_PROMPT_ROLE' => 'Select role',
    'BACKEND_PROMPT_STATUS' => 'Select status',
    'BACKEND_UPDATE_SUBMIT' => 'Update',
    'BACKEND_UPDATE_TITLE' => 'Update user',
    'BACKEND_VIEW_TITLE' => 'User page',
    'ERROR_MSG_INVALID_OLD_PASSWORD' => 'Invalid current password',
    'ERROR_MSG_INVALID_USERNAME_OR_PASSWORD' => 'Invalid username or password',
    'FRONTEND_EMAIL_CHANGE_SUBMIT' => 'Change',
    'FRONTEND_EMAIL_CHANGE_TITLE' => 'Change e-mail address',
    'FRONTEND_INDEX_TITLE' => 'Users',
    'FRONTEND_LOGIN_OR' => 'or',
    'FRONTEND_LOGIN_RECOVERY' => 'Recover password',
    'FRONTEND_LOGIN_SUBMIT' => 'Log In',
    'FRONTEND_LOGIN_TITLE' => 'Log In',
    'FRONTEND_PASSWORD_CHANGE_SUBMIT' => 'Change',
    'FRONTEND_PASSWORD_CHANGE_TITLE' => 'Change password',
    'FRONTEND_RECOVERY_CONFIRMATION_SUBMIT' => 'Save',
    'FRONTEND_RECOVERY_CONFIRMATION_TITLE' => 'Password recovery',
    'FRONTEND_RECOVERY_SUBMIT' => 'Recover',
    'FRONTEND_RECOVERY_TITLE' => 'Password recovery',
    'FRONTEND_RESEND_SUBMIT' => 'Resend',
    'FRONTEND_RESEND_TITLE' => 'Resend e-mail confirmation',
    'FRONTEND_SIGNUP_RESEND' => 'Resend e-mail confirmation',
    'FRONTEND_SIGNUP_SUBMIT' => 'Sign Up',
    'FRONTEND_SIGNUP_TITLE' => 'Sign Up',
    'FRONTEND_UPDATE_SUBMIT' => 'Update',
    'FRONTEND_UPDATE_TITLE' => 'Update user profile',
    'STATUS_ACTIVE' => 'Active',
    'STATUS_BANNED' => 'Banned',
    'STATUS_INACTIVE' => 'Inactive',
];
